[[rules]]
type = "single"
sport = 10000
dport = 443
domain = "toutiao.com"
protocol = "all"
ip_version = "both"

[[rules]]
type = "single"
sport = 10001
dport = 443
domain = "baidu.com"
protocol = "all"
ip_version = "both"
comment = "some comment"

[[rules]]
type = "single"
sport = 10002
dport = 443
domain = "localhost"
protocol = "all"
ip_version = "both"
comment = "redirect to localhost"

[[rules]]
type = "range"
port_start = 1000
port_end = 2000
domain = "baidu.com"
protocol = "tcp"
ip_version = "both"
comment = "Both IPv4 and IPv6 support"

[[rules]]
type = "single"
sport = 9001
dport = 9099
domain = "ipv6.example.com"
protocol = "tcp"
ip_version = "ipv6"
comment = "force to nat to IPv6"
